security:
  password_hashers:
    App\Entity\User: 'auto'

  #  Chef de projet = ROLE_MANAGER
  role_hierarchy:
    ROLE_MANAGER: ROLE_USER

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppAuthenticator

      logout:
        path: app_logout
        target: app_login

  access_control:
    #  pages publiques
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/welcome, roles: PUBLIC_ACCESS }

    #  ÉNONCÉ : seuls les chefs de projet peuvent modifier les fiches Employés
    - { path: ^/team, roles: ROLE_MANAGER }

    #  ÉNONCÉ : seuls les chefs de projet peuvent créer / modifier un projet
    - { path: ^/project/new, roles: ROLE_MANAGER }
    - { path: ^/project/\d+/edit, roles: ROLE_MANAGER }
    - { path: ^/project/\d+/archive, roles: ROLE_MANAGER }

    #  le reste = connecté
    - { path: ^/, roles: ROLE_USER }
